### ISSUE TITLE
Readability features used

### ISSUE THREAD

**Issue by Chunngai** [robert1ridley/cross-prompt-trait-scoring#3]
Hello. Thank you for your work and releasing the code for the paper. 

I have a question about the readability features. I noticed the file `allreadability.pickle` in the repo which stores readability scores of each essay. What readability scores are them respectively? Can you kindly provide their names in the order of what is provided in the `allreadability.pickle` file? Thank you very much!

**Comment by robert1ridley** [comment]
I have added the code used to generate the `allreadability.pickle` file. You can refer to `create_readability_features.py` in the main project directory. The features are generated using the `readability` package (https://pypi.org/project/readability/).

**Comment by Chunngai** [comment]
It helps a lot. Thank you!
