### ISSUE TITLE
some data problem

### ISSUE THREAD

**Issue by CoderBinGe** [robert1ridley/cross-prompt-trait-scoring#4]
**Hello, I am very interested in your work, I have a small question, as shown in the screenshot below, for the training data (.pk format), how to get the score of the field in the red box?**

![2022-06-21_162205](https://user-images.githubusercontent.com/26380524/174752987-f4ed862e-fe8a-4d6d-b75e-d2ac4d11dc83.png)

**Comment by robert1ridley** [comment]
Hi, these attribute scores are provided in the ASAP++ dataset, which is from the following paper: https://aclanthology.org/L18-1187.pdf. I'm not sure whether that answers your question?

**Comment by CoderBinGe** [comment]
> Hi, these attribute scores are provided in the ASAP++ dataset, which is from the following paper: https://aclanthology.org/L18-1187.pdf. I'm not sure whether that answers your question?

Thank you for your reply, I will go and see this article you said.
